// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzDCiKjA7LiYaNwGmNfi9acVNWN-wyv8c',
    appId: '1:137984252747:web:295330c3c92d5fbaf5a6ce',
    messagingSenderId: '137984252747',
    projectId: 'jobinder-5a399',
    authDomain: 'jobinder-5a399.firebaseapp.com',
    storageBucket: 'jobinder-5a399.firebasestorage.app',
    measurementId: 'G-XZ8LGWQVF5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYA0WahOej24p4SVuf4821TmreIQ7lbpo',
    appId: '1:137984252747:android:46a78d73356bd78bf5a6ce',
    messagingSenderId: '137984252747',
    projectId: 'jobinder-5a399',
    storageBucket: 'jobinder-5a399.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOW38U05487wwVSrqq3vYYsJPo6NN12pA',
    appId: '1:137984252747:ios:06822cad7f53b0a8f5a6ce',
    messagingSenderId: '137984252747',
    projectId: 'jobinder-5a399',
    storageBucket: 'jobinder-5a399.firebasestorage.app',
    iosBundleId: 'com.example.jobinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOW38U05487wwVSrqq3vYYsJPo6NN12pA',
    appId: '1:137984252747:ios:06822cad7f53b0a8f5a6ce',
    messagingSenderId: '137984252747',
    projectId: 'jobinder-5a399',
    storageBucket: 'jobinder-5a399.firebasestorage.app',
    iosBundleId: 'com.example.jobinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzDCiKjA7LiYaNwGmNfi9acVNWN-wyv8c',
    appId: '1:137984252747:web:45e8b02ce5393a7df5a6ce',
    messagingSenderId: '137984252747',
    projectId: 'jobinder-5a399',
    authDomain: 'jobinder-5a399.firebaseapp.com',
    storageBucket: 'jobinder-5a399.firebasestorage.app',
    measurementId: 'G-9KCR8PXYTY',
  );
}
